
CREATE TABLE CLIENT_INFO(
    CLIENT_ID NUMBER(13) PRIMARY KEY,                                    -- 전화번호
    CLIENT_PW VARCHAR2(30) NOT NULL,                                     -- 비밀번호
    CLIENT_NAME VARCHAR2(50) NOT NULL,                                   -- 회원명
    REGION_ID VARCHAR2(50) NOT NULL,                                      -- 지역ID
    RELIABLIITY NUMBER(3) DEFAULT 0 CHECK(RELIABLIITY BETWEEN 0 AND 100) -- 신뢰도 
)
;

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(10) PRIMARY KEY,  -- 상품ID
    PRODUCT_NAME VARCHAR2(50) NOT NULL, -- 상품명
    PRODUCT_DESCRIPTION VARCHAR(200),   -- 상품설명
    CLIENT_ID NUMBER(13) NOT NULL,      -- 회원ID
    PRICE NUMBER(9) NOT NULL            -- 가격
)
;

DROP TABLE CHATROOM;

CREATE TABLE CHATROOM(
    ROOM_ID NUMBER(10) PRIMARY KEY, --방ID
    SELLER_ID NUMBER(13) NOT NULL, --판매자ID
    BUYER_ID NUMBER(13) NOT NULL
);
INSERT INTO CHATROOM VALUES(0, 0, 0);

DROP TABLE CHATMESSAGE;

CREATE TABLE CHATMESSAGE(
    MESSAGE_ID NUMBER(10) PRIMARY KEY, --메세지ID
    MESSAGE_CONTENTS VARCHAR2(100), --메세지내용
    SENDTIME TIMESTAMP NOT NULL, --저장시간
    CLIENT_ID NUMBER(13) NOT NULL, --회원ID
    CLIENT_NAME VARCHAR2(50) NOT NULL,  --회원이름
    ROOM_ID NUMBER(10) NOT NULL --방ID
);
INSERT INTO CHATMESSAGE VALUES(0, '숫자는 보통 왼쪽부터 세는데', sysdate, 0, '우리가1조? 왜죠?', 0);

COMMIT;
